/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LineChart: typeof import('./components/Echarts/LineChart.vue')['default']
    PanThumb: typeof import('./components/PanThumb/index.vue')['default']
    PieChart: typeof import('./components/Echarts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./components/Upload/index.vue')['default']
    UploadExcel: typeof import('./components/UploadExcel/index.vue')['default']
    WebKitChart: typeof import('./components/Echarts/WebKitChart.vue')['default']
  }
}
