<template>
    <section class="main">
        <div class="logo">
            <h1>EchoVerse Management System </h1>
        </div>
        <div class="content-w3ls">
            <el-form status-icon autoComplete="on" :model="loginForm" :rules="loginRules"
                     ref="postFormRef" label-position="left">
                <el-input name="username" type="text" v-model="loginForm.username" autoComplete="on"
                          placeholder="Username"
                          :prefix-icon="User"/>


                <el-input name="password" type="password" @keyup.enter.native="handleLogin"
                          v-model="loginForm.password" autoComplete="on"
                          placeholder="Password"
                          :prefix-icon="Unlock"/>


                <div class="login_code" v-if="is_login_code">

                    <el-input
                        name="loginCode"
                        type="number"
                        @keyup.enter.native="handleLogin"
                        v-model="loginForm.loginCode"
                        autoComplete="off"
                        placeholder="Verification code" style="width:160px"
                        :prefix-icon="Coin"/>


                    <img v-if="loginCode_img_src!=''" title="Click to change verification code"
                         style="width:120px;height:54px;margin-left:10px;border-radius: 35px;cursor:pointer; "
                         :src="loginCode_img_src"
                         @click="get_login_code()"
                    />


                </div>
                <el-button :loading="loading" @click="handleLogin">Login</el-button>
            </el-form>
        </div>

        <div class="copyright">
            <router-link to="/default">
                Back to Home
            </router-link>
        </div>
    </section>
</template>

<script name="login" setup>
import store from '@/store'    // For getting cached user information
const postFormRef = ref(null) // Use this ref if the page has a form
const route = useRoute();   // Get route information or parameters
const router = useRouter();   // Handle route operations like navigation
import {ElMessage, ElMessageBox} from "element-plus";  // Alert boxes and messages
import {User, Unlock, Coin} from '@element-plus/icons-vue'

import axios_request from '@/utils/axios_request'
import {mapGetters} from "vuex";




const loginForm = ref({
    username: '',
    password: '',
    role_id: '0',
    loginCode: '',
    loginCode_create: ''
})

const loginRules = {
    username: [{required: true, message: "Please enter username", trigger: 'blur'}],
    password: [{required: true, message: "Please enter password", trigger: 'blur'}]
}

const loading = ref(false)// Loading indicator


const loginCode_img_src = ref('')// Captcha image URL from backend
const loginCode_create = ref('')// Captcha generated by backend
const is_login_code = ref(true)// Whether to enable captcha
const auto_fill_login_username = ref(true)// Whether to enable username autofill


// Get post-login information


const token = computed(() => {
    return store.getters.token
})
const username = computed(() => {
    return store.getters.username
})
const role_id = computed(() => {
    return Number(store.getters.role_id)
})
const info = computed(() => {

    return store.getters.info
})



const managerid = computed(() => {
    return store.getters.managerid
})


onMounted(() => {
    nextTick(() => {

        get_login_code()


    })
})

function get_login_code() {
    axios_request.get(
        '/system/getCpacha.action?vl=4&w=120&h=40&type=loginCpacha'
    ).then(response => {
        loginCode_img_src.value = (response.data.base64)

        auto_fill_login_username.value = response.data.auto_fill_login_username
        is_login_code.value = response.data.is_login_code
        loginCode_create.value = response.data.login_code

        // if (auto_fill_login_username.value) {
        //     loginForm.value = {
        //         username: 'manager',
        //         password: '111111',
        //         role_id: '0',
        //         loginCode: loginCode_create.value,

        //     }

        // }
        loginForm.value.loginCode_create = loginCode_create.value
    })

}

function handleLogin() {
    if (is_login_code.value && loginCode_create.value !== loginForm.value.loginCode) {
        ElMessage.error("Incorrect captcha, please re-enter")

        return
    }
    postFormRef.value.validate(valid => {
        if (valid) {
            loading.value = true
            store.dispatch('SetStoreLoginByusername', loginForm.value).then(response => {

                loading.value = false
                router.push({path: '/manager/default'})
                //location.reload()// Full page reload to force refresh navbar cache

            }).catch(err => {
                //console.log(err)
                loading.value = false
                ElMessage.error(err)

                //return false
            })
        } else {
            //console.log('error submit!!')
            return false
        }
    })
}


</script>

<style lang="scss" scoped>


.login_code {
    display: flex;
    flex-wrap: wrap;
    flex: 1;
    line-height: 32px;
    position: relative;

}

.main:before {
    position: absolute;
    content: '';
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    z-index: -1;
}

.main {
    background: url(../../../static/login.jpg);
    background-size: 100% 100%;

    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    -ms-background-size: cover;
    height: 100vh;
    position: relative;
    z-index: 1;
    justify-content: center;
    display: grid;
    align-items: center;

    .logo h1 {

        padding-top: 150px;
        font-size: 42px;
        color: #fff;
        text-transform: capitalize;
        font-weight: bold;
        text-align: center;
    }

    .content-w3ls {
        margin: 1em auto;
        width: 350px;
        text-align: center;


        .el-input {
            width: 100%;
            font-size: 16px;
            color: #999;
            letter-spacing: 0.5px;
            background: #fff;
            box-sizing: border-box;
            font-family: 'Noto Sans JP', sans-serif;
            height: 54px;
            border-radius: 35px;
            -webkit-border-radius: 35px;
            -moz-border-radius: 35px;
            -ms-border-radius: 35px;
            -o-border-radius: 35px;
            margin-bottom: 14px;
        }


        :deep(.el-icon) {

            color: #5f5f5f;
            font-size: 20px;
            font-weight: bold;


        }

        .el-radio-group {
            padding-bottom: 15px;

        }

        .el-button {


            padding: 14px 30px;
            font-size: 16px;
            color: #fff;
            letter-spacing: 0.5px;
            box-sizing: border-box;
            width: 100%;
            height: 54px;
            border-radius: 405px;

            background: linear-gradient(130deg, #2E68EC 0%, #2E68EC 100%);
            box-shadow: 0 0 10px 0 rgba(255, 255, 255, 1.4);
            border: 1px solid #E3E5E7;
            letter-spacing: 20px;

        }
    }

    .copyright {
        padding: 0 20px;
        text-align: center;
        color: rgba(255, 255, 255, .9);

        p {

            font-size: 16px;
            line-height: 26px;
            letter-spacing: 1px;

        }

        a {
            color: #ccffcc;
            text-shadow: 0 0 5px rgba(255, 255, 255, .9);
            font-weight: bold;
            display: block;
            font-size: 18px;
        }
    }
}


</style>
