package com.entity;

public class Projectinfo {


    private String projectinfo_typename;
     private String projectinfo_files;//
    private String membersid;
    private String username;

    private Integer projectinfo_0;
    private String keyword_table;//
    private String projectinfo_istop;//
    private String projectinfo_isflv;//
    private String projectinfo_hits;//
    private String projectinfo_artist;//
    private String projectinfo_album;//
    private String projectinfo_3;//
    private String projectinfo_4;//
    private String projectinfo_5;//
    private String projectinfo_6;//


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.projectinfoid
     *
     * @mbggenerated
     */
    private Integer projectinfoid;
    private String projectinfo_typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.status
     *
     * @mbggenerated
     */
    private Integer status;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.iscooled
     *
     * @mbggenerated
     */
    private Integer iscooled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.projectinfoid
     *
     * @return the value of projectinfo.projectinfoid
     * @mbggenerated
     */
    public Integer getProjectinfoid() {
        return projectinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.projectinfoid
     *
     * @param projectinfoid the value for projectinfo.projectinfoid
     * @mbggenerated
     */
    public void setProjectinfoid(Integer projectinfoid) {
        this.projectinfoid = projectinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.status
     *
     * @return the value of projectinfo.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.status
     *
     * @param status the value for projectinfo.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.projectinfo_0
     *
     * @return the value of projectinfo.projectinfo_0
     * @mbggenerated
     */
    public Integer getprojectinfo_0() {
        return projectinfo_0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.projectinfo_0
     *
     * @param projectinfo_0 the value for projectinfo.projectinfo_0
     * @mbggenerated
     */
    public void setprojectinfo_0(Integer projectinfo_0) {
        this.projectinfo_0 = projectinfo_0;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.keyword_table
     *
     * @return the value of projectinfo.keyword_table
     * @mbggenerated
     */
    public String getKeyword_table() {
        return keyword_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.keyword_table
     *
     * @param keyword_table the value for projectinfo.keyword_table
     * @mbggenerated
     */
    public void setKeyword_table(String keyword_table) {
        this.keyword_table = keyword_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.iscooled
     *
     * @return the value of projectinfo.iscooled
     * @mbggenerated
     */
    public Integer getIscooled() {
        return iscooled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.iscooled
     *
     * @param iscooled the value for projectinfo.iscooled
     * @mbggenerated
     */
    public void setIscooled(Integer iscooled) {
        this.iscooled = iscooled;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.projectinfoname
     *
     * @mbggenerated
     */
    private String projectinfoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.createdate
     *
     * @mbggenerated
     */
    private String createdate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.projectinfoname
     *
     * @return the value of projectinfo.projectinfoname
     * @mbggenerated
     */
    public String getProjectinfoname() {
        return projectinfoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.projectinfoname
     *
     * @param projectinfoname the value for projectinfo.projectinfoname
     * @mbggenerated
     */
    public void setProjectinfoname(String projectinfoname) {
        this.projectinfoname = projectinfoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.image
     *
     * @return the value of projectinfo.image
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.image
     *
     * @param image the value for projectinfo.image
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.remark
     *
     * @return the value of projectinfo.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.remark
     *
     * @param remark the value for projectinfo.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.createdate
     *
     * @return the value of projectinfo.createdate
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.createdate
     *
     * @param createdate the value for projectinfo.createdate
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }


    public String getProjectinfo_typeid() {
        return projectinfo_typeid;
    }

    public void setProjectinfo_typeid(String projectinfo_typeid) {
        this.projectinfo_typeid = projectinfo_typeid;
    }

    public String getProjectinfo_typename() {
        return projectinfo_typename;
    }

    public void setProjectinfo_typename(String projectinfo_typename) {
        this.projectinfo_typename = projectinfo_typename;
    }


    public String getProjectinfo_files() {
        return projectinfo_files;
    }

    public void setProjectinfo_files(String projectinfo_files) {
        this.projectinfo_files = projectinfo_files;
    }

    public String getMembersid() {
        return membersid;
    }

    public void setMembersid(String membersid) {
        this.membersid = membersid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    public String getProjectinfo_istop() {
        return projectinfo_istop;
    }

    public void setProjectinfo_istop(String projectinfo_istop) {
        this.projectinfo_istop = projectinfo_istop;
    }

    public String getProjectinfo_isflv() {
        return projectinfo_isflv;
    }

    public void setProjectinfo_isflv(String projectinfo_isflv) {
        this.projectinfo_isflv = projectinfo_isflv;
    }

    public String getProjectinfo_hits() {
        return projectinfo_hits;
    }

    public void setProjectinfo_hits(String projectinfo_hits) {
        this.projectinfo_hits = projectinfo_hits;
    }

    public String getProjectinfo_6() {
        return projectinfo_6;
    }

    public void setProjectinfo_6(String projectinfo_6) {
        this.projectinfo_6 = projectinfo_6;
    }

    public String getProjectinfo_artist() {
        return projectinfo_artist;
    }

    public void setProjectinfo_artist(String projectinfo_artist) {
        this.projectinfo_artist = projectinfo_artist;
    }

    public String getProjectinfo_album() {
        return projectinfo_album;
    }

    public void setProjectinfo_album(String projectinfo_album) {
        this.projectinfo_album = projectinfo_album;
    }

    public String getProjectinfo_3() {
        return projectinfo_3;
    }

    public void setProjectinfo_3(String projectinfo_3) {
        this.projectinfo_3 = projectinfo_3;
    }

    public String getProjectinfo_4() {
        return projectinfo_4;
    }

    public void setProjectinfo_4(String projectinfo_4) {
        this.projectinfo_4 = projectinfo_4;
    }

    public String getProjectinfo_5() {
        return projectinfo_5;
    }

    public void setProjectinfo_5(String projectinfo_5) {
        this.projectinfo_5 = projectinfo_5;
    }
}
