<template>
    <div>
        <el-form
            status-icon :model="postForm" :rules="rules"
            ref="postFormRef" label-width="120px"
            size="small"
        >

            <el-form-item label=" Category" prop="projectinfo_typeid">
                <el-select size="small" v-model="postForm.projectinfo_typeid" placeholder="Please select">
                    <el-option
                        v-for="item in projectinfo_typeOptions"
                        :key="item.projectinfo_typeid"
                        :label="item.projectinfo_typename"
                        :value="item.projectinfo_typeid">
                    </el-option>
                </el-select>
            </el-form-item>
            <el-form-item label=" Name" prop="projectinfoname">
                <el-input placeholder="Please enter" v-model="postForm.projectinfoname"/>
            </el-form-item>
            <el-form-item label=" Album" prop="projectinfo_album">
                <el-input placeholder="Please enter" v-model="postForm.projectinfo_album"/>
            </el-form-item>
            <el-form-item label=" Artist" prop="projectinfo_artist">
                <el-input placeholder="Please enter" v-model="postForm.projectinfo_artist"/>
            </el-form-item>

            <el-form-item label="Keyword" prop="keyword_table">
                <el-input style="width: 290px" placeholder="Please enter" v-model="postForm.keyword_table"/>

            </el-form-item>
            <el-form-item label="Image" prop="image">
                <Upload v-model="postForm.image" accept=".jpg,.png,.gif"/>
            </el-form-item>
            <el-form-item label="Attachment File" prop="projectinfo_files">
                <Upload v-model="postForm.projectinfo_files" accept=".mp3"/>
            </el-form-item>
            <el-form-item label="Content" prop="remark">


                <vue-ueditor-wrap
                    v-model="postForm.remark"
                    :config="ueditorconfig1"
                    style="line-height:20px"/>

            </el-form-item>


        </el-form>

        <div class="dialog-footer">
            <el-button type="primary" @click="saveData" icon="coin">Save</el-button>
        </div>

    </div>
</template>


<script name="dialogForm" setup>
import store from '@/store'    // For getting cached user information
const postFormRef = ref(null) // Form reference if page contains form
const route = useRoute();   // Get route information and parameters
const router = useRouter();   // Handle route operations like navigation
import {ElMessage, ElMessageBox} from "element-plus";  // Notifications and message boxes


import axios_request from '@/utils/axios_request'
import {mapGetters} from "vuex";

import {
    pickerRangOptions,
    pickerRangNoAfterOptions,
    pickerDayNoAfterOptions,
    pickerDayUseAfterOptions,
    pickerDayNobefoOptions
} from '@/components/mixin/mixin_publicData'  // Some common DATA parameters, such as date selection parameters

import Upload from '@/components/Upload'

let formData = {
    projectinfoname: '',
    image: '',
    remark: '',
    keyword_table: '',

  projectinfo_istop: 'No',
        projectinfo_isflv: 'No',
}


const props = defineProps({

    // Data ID, only used in this component
    dataId: {
        type: Number,
        default: 0
    },
    // Hide and show, for monitoring and initialization, only used in this component
    dialogFormVisible: {
        type: Boolean,
        default: false
    },

});


const postForm = ref({})// Form

const rules = {
    projectinfoname: [{required: true, message: "Please fill in"}],
    keyword_table: [{required: false, message: "Optional field"}],


}

const projectinfo_typeOptions = ref({});// Comment here

const ueditorconfig1 = {
    // Multimedia editor configuration
    headers: {
        token: localStorage.getItem("Manager-Token") // Token passed to the resource server
    },
    serverUrl: null,
    // UEditor resource file storage path, if you use a project generated by vue-cli, usually you don't need to set this option, vue-ueditor-wrap will automatically handle common situations, if you need special configuration, refer to the common questions 2 below
    UEDITOR_HOME_URL: '/UEditor/',
    // Initial container height
    initialFrameHeight: 300,
    // Initial container width
    initialFrameWidth: '100%',
    // Editor not automatically stretched by content
    autoHeightEnabled: false,
}


watch(() => props.dataId, newdata => {
    //console.log('Detected change')
    fetchData()// Update form values based on ID change

}, {deep: true})

watch(() => props.dialogFormVisible, newdata => {
    //console.log('Detected change')
    postForm.value = JSON.parse(JSON.stringify(formData))// Deep copy a data template for form initialization
    if (newdata) fetchData()// Monitor whether the popup is displayed, if displayed, initialize the data

}, {deep: true})

// Get login information
const token_front = computed(() => {
    return store.getters.token_front
})
const info_front = computed(() => {
    return store.getters.info_front
})
const userid_front = computed(() => {
    return store.getters.userid_front
})


const token = computed(() => {
    return store.getters.token
})
const username = computed(() => {
    return store.getters.username
})
const role_id = computed(() => {
    return Number(store.getters.role_id)
})
const info = computed(() => {

    return store.getters.info
})

const role_front = computed(() => {
    return store.getters.role_front
})


// Initialization

onMounted(() => {
    postForm.value = JSON.parse(JSON.stringify(formData))// Deep copy a data template for form initialization

    if (route.query.id) props.dataId = route.query.id// If it's a route edit interface (not popup interface) opened directly in the menu, get ID from route
    fetchData()
    // Deep copy a data template for form initialization

})


// Close popup
const emits = defineEmits(['close'])

function closeDialog() {
    // When closing, cannot restore data, if restore, will cause child component to pass the wrong row data to parent component
    emits('close') // Event notification to parent component to modify el-model display status
}

// Get data and initialize
function fetchData() {
    if (props.dataId > 0) {
        // Show edit data
        axios_request.get('/front/getById.action?id=' + props.dataId).then(response => {
                if (response.data) {
                    projectinfo_typeOptions.value = response.data.projectinfo_typeList
                    postForm.value = response.data.projectinfo
                }
            }
        )
    } else {
        // Show add data
        axios_request.get('/front/create.action').then(response => {
                if (response.data) {
                    projectinfo_typeOptions.value = response.data.projectinfo_typeList
                    postForm.value.projectinfo_typeid = response.data.projectinfo_typeList[0].projectinfo_typeid// First open, default select first one

                }
            }
        )
    }

}


// Save data
function saveData() {
    postFormRef.value.validate((valid) => {
        if (valid) {
            axios_request.post('/front/' + (props.dataId > 0 ? 'update' : 'add') + '.action', postForm.value).then(response => {
                if (response.code === 200) {
                    ElMessage({
                        type: 'success',
                        message: response.message || (props.dataId > 0 ? 'Update successful' : 'Add successful')
                    })
                    emits('close')
                } else {
                    ElMessage({
                        type: 'error',
                        message: response.message || 'Operation failed, you can only edit music files you uploaded'
                    })
                }
            }).catch(error => {
                ElMessage({
                    type: 'error',
                    message: 'Operation failed, please try again later'
                })
            })
        }
    })
}

</script>
